services:
  - type: web
    name: my-portfolio-api
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CORS_ORIGIN
        value: https://lighthouse2815.github.io
